name: Selenium E2E test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Cucumber tests on Chrome
        run: mvn clean test -Dbrowser=CHROME

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest

      - name: Run Cucumber tests on Firefox
        run: mvn clean test -Dbrowser=FIREFOX

      - name: Setup Edge
        uses: browser-actions/setup-edge@latest

      - name: Run Cucumber tests on Edge
        run: mvn clean test -Dbrowser=EDGE

      - name: Get Allure history
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        id: allure-report
